// weather-svelte/src/App.svelte
<script>
  import "./index.css";

  import ContentCollumn from "./components/ContentCollumn.svelte";
  import DailyComponent from "./components/DailyComponent.svelte";
  import LabeledText from "./components/LabeledText.svelte";
import { loop_guard } from "svelte/internal";

  const tkid = import.meta.env.VITE_TKID;

  const getBRLNumbers = (num) =>
    Intl.NumberFormat("pt-BR", {
      maximumSignificantDigits: 1,
    }).format(num);

  const convertMsToKmh = (ms = 0) => ms * 3.6;

  const extractEvent = () => Array.from(document.scripts)
    .filter((script) => script.type === "application/ld+json")
    .map((script) => JSON.parse(script.textContent));

  const getEventDates = () => extractEvent().map((event) => ({
      startDateTimestamp: +new Date(event.startDate),
      endDateTimestamp: +new Date(`${event.endDate}T18:59:59`),
    })).pop();

  const getLatLongFromPage = () => {
    const Event = extractEvent().filter((script) => script["@type"] === "BroadcastEvent").pop();
 
    const loc = Event.broadcastOfEvent.location.filter(location => location['@type'] === 'Place').pop();
    
    return loc.geo;
  }

  const fetchWeather = () => {
    const {latitude, longitude} = getLatLongFromPage();

    return fetch(
      `https://api.openweathermap.org/data/2.5/onecall?lat=${latitude}&lon=${longitude}&exclude=minutely,hourly&appid=${tkid}&units=metric&lang=pt_br`
    ).then((response) => response.json());
  }

  const {startDateTimestamp, endDateTimestamp} = getEventDates();
</script>

<div class="track-weather">
  {#await fetchWeather()}
    Carregando...
  {:then weather}
    {#if weather.current}
      <div class="row display-flex">
        <ContentCollumn num="1">
          <p class="temp">
            {getBRLNumbers(weather.current.temp)}º <br />
          </p>
          <p class="temp-description">
            {weather.current.weather[0].description}
          </p>
        </ContentCollumn>

        <ContentCollumn num="2">
          <LabeledText label="Sensação térmica">
            {getBRLNumbers(weather.current.feels_like)}º
          </LabeledText>
          <LabeledText label="Humidade do Ar">
            {weather.current.humidity}%
          </LabeledText>
          <LabeledText label="Pressão Atmosférica">
            {weather.current.pressure}hPa
          </LabeledText>
        </ContentCollumn>

        <ContentCollumn num="3">
          <LabeledText label="Velocidade do Vento">
            {getBRLNumbers(convertMsToKmh(weather.current.wind_speed))}km/h
          </LabeledText>
          <LabeledText label="Rajadas de Vento">
            {getBRLNumbers(convertMsToKmh(weather.current.wind_gust))}km/h
          </LabeledText>
          <LabeledText label="Direção do Vento">
            {weather.current.wind_deg}º
          </LabeledText>
        </ContentCollumn>
      </div>
      <h4>Previsão para os próximos dias</h4>
      <div class="display-flex row daily-temps">
        {#each weather.daily.filter(({dt}, i) =>
          (dt * 1000 >= startDateTimestamp && dt * 1000 <= endDateTimestamp && i < 4)) as daily}
          <DailyComponent dailyWeather={daily} {getBRLNumbers} />
        {/each}
      </div>
    {/if}
  {/await}
</div>

// react-version/src/App.jsx
import { useState, useEffect } from 'react';
import './App.css';

import {DailyComponent} from './DailyComponent';

import {LabeledText} from './LabeledText';

const tkid = '0e302008d450a0efe734fc51ba7292c3'// process.env.OPENWEATHER_API_KEY;

const getBRLNumbers = num => 
  Intl.NumberFormat('pt-BR', { maximumSignificantDigits: 1 }).format(num);

const convertMsToKmh = (ms = 0) => ms * 3.6;

const ContentCollumn = ({num, children}) => (
  <div className={`col-${num}`}>
    {children}
  </div>
);

function App({coords}) {

  const [weather, setWeather] = useState({});

  async function getWeekWeather(coords) {
    const {lat, long} = coords;

    const result = await fetch(`https://api.openweathermap.org/data/2.5/onecall?lat=${lat}&lon=${long}&exclude=minutely,hourly&appid=${tkid}&units=metric&lang=pt_br`);
    const wheaterResult = await result.json();

    setWeather(wheaterResult);
  }

  useEffect(() => {
    getWeekWeather(coords);
  }, [coords]);

  return (
    <div className="track-weather">
      {
        weather.current && 
          <div className="row display-flex">
            <ContentCollumn num="1">
              <p className="temp">
                {getBRLNumbers(weather.current.temp)}º <br/>
              </p>
              <p class="temp-description">
                {weather.current.weather[0].description}
              </p>
            </ContentCollumn>

            <ContentCollumn num="2">
              <LabeledText label="Sensação térmica">
                {getBRLNumbers(weather.current.feels_like)}º
              </LabeledText>
              <LabeledText label="Humidade do Ar">
                {weather.current.humidity}%
              </LabeledText>
              <LabeledText label="Pressão Atmosférica">
                {weather.current.pressure}hPa
              </LabeledText>
            </ContentCollumn>

            <ContentCollumn num="3">
              <LabeledText label="Velocidade do Vento">
                {
                  getBRLNumbers(
                    convertMsToKmh(weather.current.wind_speed))  
                }km/h
              </LabeledText>
              <LabeledText label="Rajadas de Vento">
                {
                  getBRLNumbers(
                    convertMsToKmh(weather.current.wind_gust))
                }km/h
              </LabeledText>
              <LabeledText label="Direção do Vento">
                {weather.current.wind_deg}º
              </LabeledText>
            </ContentCollumn>
          </div>
      }

      <div className="display-flex row daily-temps">
        {
          weather.daily && weather.daily.filter((_, i) => i < 3).map(daily => 
            <DailyComponent dailyWeather={daily} getBRLNumbers={getBRLNumbers}>
            </DailyComponent>)
        }
      </div>
    </div>
  );
}

export default App;
