// react-version/src/DailyComponent.jsx
import { LabeledText } from './LabeledText';

export const DailyComponent = ({ dailyWeather, getBRLNumbers }) => (<div>
  <p className="daily-temp">{getBRLNumbers(dailyWeather.temp.day)}º</p>

  <p className="date">
    <LabeledText label={
      dailyWeather.weather[0].description
    }>
    </LabeledText>

    {(new Date(dailyWeather.dt * 1000).toLocaleDateString('pt-BR', {
      weekday: 'short',
      day: 'numeric',
    }))}
  </p>
</div>)

// weather-svelte/src/components/DailyComponent.svelte
<script> 
  export let dailyWeather; 
  export let getBRLNumbers;
</script>

<div class="daily-section">
  <p class="date">
    {
      new Date(dailyWeather.dt * 1000).toLocaleDateString('pt-BR', {
        weekday: 'short',
        day: 'numeric',
      })
    }
  </p>
  
  <p class="daily-temp">{getBRLNumbers(dailyWeather.temp.day)}º</p>

  <p class="text-label">
    {dailyWeather.weather[0].description}
  </p>
</div>
